name = "GinzburgLandau"
uuid = "2b93a7a2-2b50-4ace-b746-62d408a4cb6c"
authors = ["Maximilian Gelbrecht <maximilian.gelbrecht@posteo.de> and contributors"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
